global:
  scrape_interval: 2s # 빠른 모니터링을 위해 2초마다 수집

scrape_configs:
  - job_name: 'moju-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # mozu-spring 서버 프라이빗 IP로 변경 (멀티 서버 배포 환경)
      - targets: ['172.31.14.21:8080']